name: Build Paper 
on: 
  push:
    paths:
      - 'tex/**'
      - '.github/workflows/latex.yml'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile ACM Paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          working_directory: "tex/acmpaper"
      - name: Compile Type2023 Paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: types2023.tex
          working_directory: "tex/types2023"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            tex/acmpaper/paper.pdf
            tex/types2023/types2023.pdf
