name: Python Library UnitTests

on:
  push:
    paths:
      - 'code/LayeredTypes/**'
      - '.github/workflows/python_unittests.yml'


steps:
- uses: actions/checkout@v3
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'
    cache: 'pip'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
- name: Test with pytest
  run: |
    pip install pytest
    python -m pytest tests/ 

defaults:
  run:
    working-directory: code/LayeredTypes
